var searchData=
[
  ['ratelimit_0',['RateLimit',['../classRateLimit.html',1,'']]],
  ['read_1',['read',['../classAPIs.html#ab9bc706a53fb8ec8386650e4c217be5b',1,'APIs']]],
  ['register_2ehpp_2',['register.hpp',['../register_8hpp.html',1,'']]],
  ['route_5flogin_3',['ROUTE_Login',['../login_8cpp.html#a00f361d5fb17810dec7d8826a2496d2b',1,'ROUTE_Login(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;sqlAPI):&#160;login.cpp'],['../login_8hpp.html#a00f361d5fb17810dec7d8826a2496d2b',1,'ROUTE_Login(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;sqlAPI):&#160;login.cpp']]],
  ['route_5fproblem_4',['ROUTE_problem',['../problem_8cpp.html#a8cb3f56e94b8d95fe028d6cd15a64cad',1,'ROUTE_problem(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;sqlAPI, cache::lru_cache&lt; int16_t, nlohmann::json &gt; &amp;problem_cache):&#160;problem.cpp'],['../problem_8hpp.html#a8cb3f56e94b8d95fe028d6cd15a64cad',1,'ROUTE_problem(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;sqlAPI, cache::lru_cache&lt; int16_t, nlohmann::json &gt; &amp;problem_cache):&#160;problem.cpp']]],
  ['route_5fproblems_5',['ROUTE_problems',['../problems_8cpp.html#a3b34d447ce222e94e1ebde7107cde756',1,'ROUTE_problems(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;API, cache::lru_cache&lt; int8_t, nlohmann::json &gt; &amp;problems_everyone_cache, std::atomic&lt; bool &gt; &amp;problems_everyone_cache_hit):&#160;problems.cpp'],['../problems_8hpp.html#a3b34d447ce222e94e1ebde7107cde756',1,'ROUTE_problems(crow::App&lt; crow::CORSHandler &gt; &amp;app, nlohmann::json &amp;settings, std::string IP, std::unique_ptr&lt; APIs &gt; &amp;API, cache::lru_cache&lt; int8_t, nlohmann::json &gt; &amp;problems_everyone_cache, std::atomic&lt; bool &gt; &amp;problems_everyone_cache_hit):&#160;problems.cpp']]],
  ['route_5fregister_6',['ROUTE_Register',['../register_8hpp.html#ac0f8312d3b5e9958ea002d76ee814223',1,'register.cpp']]]
];
